version: '3'
services:
  electorator-db:
    image: postgres:12.6
    restart: always
    volumes:
      - ../electorator-data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    env_file:
      - ../electorator.env